# Changes here will be overwritten by Copier
_commit: v0.4.1
_src_path: gh:linkml/linkml-project-copier
add_example: false
copyright_year: '2025'
email: Robert.Carroll@vumc.org
full_name: Robert Carroll
gh_action_docs_preview: true
gh_action_pypi: false
github_org: anvilproject
license: MIT
project_description: LinkML Schema for ACR Harmonized Data.
project_name: acr-harmonized-data-model
project_slug: acr_harmonized_data_model

