# Changes here will be overwritten by Copier
_commit: v0.1.7
_src_path: gh:linkml/linkml-project-copier
copyright_year: '2025'
create_python_classes: 'Yes'
email: Robert.Carroll@vumc.org
full_name: Robert Carroll
github_org: anvilproject
license: MIT
main_schema_class: Person
project_description: LinkML Schema for ACR Harmonized Data.
project_name: acr-harmonized-data-model
project_slug: acr_harmonized_data_model
use_schemasheets: 'No'

