name: Data Model Type Request
about: Request a data type not currently included in the harmonized data model
title: "[Data Type Request]: "
labels: ["request"]
projects: ["Data Model Requests"]
assignees: 
  - SophieFormanVUMC

feature_request:
  - question: "**Is your feature request related to a problem? Please describe.**"
    description: "A clear and concise description of what the problem is. Ex. My team collects X type of data that is not currently included in the AnVIL data model, and we'd like to include it."
    text_box: "Enter details here..."

  - question: "**Describe the solution you'd like**"
    description: "A clear and concise description of what you want to happen."
    text_box: "Enter solution here..."

  - question: "**Describe alternatives you've considered**"
    description: "A clear and concise description of any alternative solutions or features you've considered."
    text_box: "Enter alternatives here..."

  - question: "**Was the request brought to an AnVIL workgroup?**"
    description: "If yes, which one, when, and what was the feedback received?"
    text_box: "Enter workgroup details here..."

  - question: "**Additional context**"
    description: "Add any other context or screenshots about the feature request here."
    text_box: "Enter additional context here..."
