name: Data Model Type Request
description: Request a data type not currently included in the harmonized data model
title: "[Data Type Request]: "
labels: ["request"]
projects: ["Data Model Requests"]
assignees: 
  - SophieFormanVUMC

body:
- type: input
  attributes:
    label: "What is the data type you are requesting to be added to the AnVIL Data Model?"
    description: "A clear and concise description of the data type being requested."
    placeholder: "Enter details here..."

- type: textarea
  attributes:
    label: "Is your feature request related to a problem? Please describe."
    description: "A clear and concise description of what the problem is, and who it impacts. Ex: My team collects X type of data that is not currently included in the AnVIL data model, and we'd like to include it."
    placeholder: "Enter details here..."

- type: textarea
  attributes:
    label: "Describe the solution you'd like"
    description: "A clear and concise description of what you want to happen."
    placeholder: "Enter solution here..."

- type: textarea
  attributes:
    label: "Describe alternatives you've considered"
    description: "A clear and concise description of any alternative solutions or features you've considered."
    placeholder: "Enter alternatives here..."

- type: dropdown
  attributes:
    label: "Was the request brought to an AnVIL workgroup?"
    options:
      - "Yes"
      - "No"

- type: input
  attributes:
    label: "If yes, which workgroup?"

- type: input
  attributes:
    label: "What date?"

- type: textarea
  attributes:
    label: "If yes, what was the feedback received?"
    placeholder: "Enter details here..."

- type: textarea
  attributes:
    label: "Additional context"
    description: |
      "Links? References? Anything that will give us more context about the issue you are encountering!
      
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in."
