name: Data Model Type Request
description: Request a data type not currently included in the ACR harmonized data model
title: "[Data Type Request]: "
labels: ["request"]
projects: ["Data Model Requests"]
assignees: 
  - SophieFormanVUMC

body:
- type: input
  attributes:
    label: "If you are submitting the request for someone other than yourself, who is the request for?"
    placeholder: "Name, affiliation, contact information"
- type: input
  attributes:
    label: "What is the data type you are requesting to be added to the ACR Data Model?"
    description: "A clear and concise description of the data type being requested."
    placeholder: "Enter details here..."
- type: textarea
  attributes:
    label: "What are use cases for this requested addition, and/or what problem is this feature request aiming to solve? Is this request time-sensitive?"
    description: ""A clear and concise description of the use cases for this feature request, what the problem is, and who it impacts. Ex: My team collects X type of data that is not currently included in the AnVIL data model, and we'd like to include it to submit in May 2025."
    placeholder: "Enter details here..."
- type: textarea
  attributes:
    label: "What timeline are you envisioning?"
    placeholder: "Enter timeline details here..."
- type: textarea
  attributes:
    label: "What consortia or groups could this support?"
    description: "For example, eMERGE, All of Us, MOHD..."
    placeholder: "Enter details here..."
- type: textarea
  attributes:
    label: "Describe the solution(s) you'd like"
    description: "A clear and concise description(s) of proposed solutions."
    placeholder: "Enter solution here..."

- type: textarea
  attributes:
    label: "If this isn't included in the data model, what are workarounds you are currently using?"
    description: "A clear and concise description of your current process or workarounds in use."
    placeholder: "Enter details here..."

- type: dropdown
  attributes:
    label: "Was the request brought to the AnVIL Phenotype Working Group?"
    description: "If not, our team will be in contact to arrange this."
    options:
      - "Yes"
      - "No"

- type: textarea
  attributes:
    label: "If yes, what was the feedback received?"
    placeholder: "Enter details here..."

- type: textarea
  attributes:
    label: "Any Additional context"
    description: |
      Insert any links, references, and/or anything that will give us more context about the issue you are encountering!
      
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
