# metamodel_version: 1.11.0
enum EnumAssertionProvenance
  {
    medical_record
    investigator_assessment
    participant_or_caregiver_report
    other
  }

enum EnumAvailabilityStatus
  {
    available
    unavailable
  }

enum EnumClinicalDataSourceType
  {
    medical_record
    investigator_assessment
    participant_or_caregiver_report
    other
    unknown
  }

enum EnumConsanguinityAssertion
  {
    not_suspected
    suspected
    known_present
    unknown
  }

enum EnumDataCategory
  {
    unharmonized_demographic_clinical_data
    harmonized_demographic_clinical_data
    genomics
    transcriptomics
    epigenomics
    proteomics
    metabolomics
    cognitive_behavioral
    immune_profiling
    imaging
    microbiome
    fitness
    physical_activity
    other
    sleep_study
  }

enum EnumEthnicity
  {
    hispanic_or_latino
    not_hispanic_or_latino
    prefer_not_to_answer
    unknown
  }

enum EnumFamilyType
  {
    control_only
    duo
    proband_only
    trio
    trio_plus
  }

enum EnumFileAvailability
  {
    snomed_ct__COLON__103328004
    snomed_ct__COLON__103329007
  }

enum EnumFileHashType
  {
    md5
    etag
    sha1
  }

enum EnumNull
  {
    unknown
  }

enum EnumParticipantLifespanStage
  {
    fetal
    neonatal
    pediatric
    adult
  }

enum EnumPresentAbsent
  {
    loinc__COLON__LA9633__HYPHEN_MINUS__4
    loinc__COLON__LA9634__HYPHEN_MINUS__2
    loinc__COLON__LA11884__HYPHEN_MINUS__6
  }

enum EnumProgram
  {
    include
    kf
    other
  }

enum EnumRace
  {
    american_indian_or_alaska_native
    asian
    black_or_african_american
    more_than_one_race
    native_hawaiian_or_other_pacific_islander
    other
    white
    prefer_not_to_answer
    unknown
    east_asian
    latin_american
    middle_eastern_or_north_african
    south_asian
  }

enum EnumResearchDomain
  {
    behavior_and_behavior_mechanisms
    congenital_heart_defects
    immune_system_diseases
    hematologic_diseases
    neurodevelopment
    sleep_wake_disorders
    all_co_occurring_conditions
    physical_fitness
    other
  }

enum EnumSex
  {
    female
    male
    other
    unknown
  }

enum EnumStudyDesign
  {
    case_control
    case_set
    control_set
    clinical_trial
    cross_sectional
    family_twins_trios
    interventional
    longitudinal
    trial_readiness_study
    tumor_vs_matched_normal
  }

enum EnumSubjectType
  {
    participant
    non_participant
    cell_line
    animal_model
    group
    other
  }

enum EnumVitalStatus
  {
    dead
    alive
  }

type AccessPolicy
  {
    accessPolicyId: CoGlobalID!
    dataUseAccession: String
    dataUsePermission: EnumDataUsePermission!
    dataUseModifier: EnumDataUseModifier
    diseaseLimitation: String
    accessDescription: String
    website: String
  }

type ActivityDefinition
  {
    externalId: [String]
    accessPolicyId: AccessPolicy
    studyId: Study
    activityDefinitionId: AdGlobalID!
    name: String
    description: String
  }

type Aliquot
  {
    externalId: [String]
    accessPolicyId: AccessPolicy
    studyId: Study
    aliquotId: String!
    sampleId: Sample
    availablityStatus: EnumAvailabilityStatus
    quantityNumber: Float
    quantityUnit: Concept
    concentrationNumber: Float
    concentrationUnit: Concept
  }

scalar Any

type Assay
  {
    externalId: [String]
    accessPolicyId: AccessPolicy
    studyId: Study
    assayId: DiGlobalID!
    subjectId: [Subject]
    sampleId: [Sample]
    fileId: [File]
    assayType: EnumAssayType!
    assaySource: String
    activityDefinitionId: ActivityDefinition
  }

type BiospecimenCollection
  {
    externalId: [String]
    accessPolicyId: AccessPolicy
    studyId: Study
    biospecimenCollectionId: String!
    ageAtCollection: Float
    method: EnumSampleCollectionMethod
    site: EnumSite
    spatialQualifier: EnumSpatialQualifiers
    laterality: EnumLaterality
    encounterId: Encounter
  }

type Concept
  {
    conceptCurie: String!
    display: String
  }

type Dataset
  {
    datasetId: LsGlobalID!
    name: String
    description: String
    doId: DOI
    fileId: [File]
    publication: [Publication]
    dataCollectionStart: String
    dataCollectionEnd: String
  }

type Demographics
  {
    externalId: [String]
    accessPolicyId: AccessPolicy
    studyId: Study
    subjectId: Subject!
    sex: EnumSex!
    race: [EnumRace]!
    ethnicity: EnumEthnicity!
    ageAtLastVitalStatus: Int
    vitalStatus: EnumVitalStatus
    ageAtFirstEngagement: Int
  }

type DOI
  {
    externalId: [String]
    accessPolicyId: AccessPolicy
    studyId: Study
    doId: String!
    bibliographicReference: String
  }

type Encounter
  {
    externalId: [String]
    accessPolicyId: AccessPolicy
    studyId: Study
    encounterId: EnGlobalID!
    subjectId: Subject
    encounterDefinitionId: EncounterDefinition
    ageAtEvent: Int
  }

type EncounterDefinition
  {
    externalId: [String]
    accessPolicyId: AccessPolicy
    studyId: Study
    encounterDefinitionId: PdGlobalID!
    name: String
    description: String
    activityDefinitionId: [ActivityDefinition]
  }

type Family
  {
    externalId: [String]
    accessPolicyId: AccessPolicy
    studyId: Study
    familyId: GrGlobalID!
    familyType: EnumFamilyType
    familyDescription: String
    consanguinity: EnumConsanguinityAssertion
    familyStudyFocus: String
  }

type FamilyMembership
  {
    externalId: [String]
    accessPolicyId: AccessPolicy
    studyId: Study
    familyMembershipId: String!
    familyId: Family!
    subjectId: Subject!
    familyRole: String
  }

type FamilyRelationship
  {
    externalId: [String]
    accessPolicyId: AccessPolicy
    studyId: Study
    familyRelationshipId: FmGlobalID!
    familyMemberId: Subject!
    relation: EnumFamilyRelation!
    subjectId: Subject!
  }

type File
  {
    externalId: [String]
    accessPolicyId: AccessPolicy
    studyId: Study
    fileId: DrGlobalID!
    subjectId: [Subject]
    sampleId: [Sample]
    filename: String
    format: EnumEDAMFormats
    fileExtension: String!
    dataCategory: EnumDataCategory
    dataType: EnumEDAMDataTypes
    size: Int
    internalUri: String
    releaseUri: String
    drsUri: String
    storageClass: String
    hash: [FileHash]
    availability: EnumFileAvailability
  }

type FileHash
  {
    hashType: EnumFileHashType
    hashValue: String
  }

type Investigator
  {
    externalId: [String]
    accessPolicyId: AccessPolicy
    studyId: Study
    name: String
    institution: String
    investigatorTitle: String
    email: String
  }

type Publication
  {
    externalId: [String]
    accessPolicyId: AccessPolicy
    studyId: Study
    bibliographicReference: String
    website: String
  }

interface Record
  {
    externalId: [String]
    accessPolicyId: AccessPolicy
    studyId: Study
  }

type Sample
  {
    externalId: [String]
    accessPolicyId: AccessPolicy
    studyId: Study
    sampleId: BsGlobalID!
    biospecimenCollectionId: BiospecimenCollection
    parentSampleId: Sample
    sampleType: String!
    processing: [String]
    availablityStatus: EnumAvailabilityStatus
    storageMethod: [String]
    quantityNumber: Float
    quantityUnit: Concept
  }

type Study
  {
    externalId: [String]
    accessPolicyId: AccessPolicy
    parentStudy: Study
    studyTitle: String!
    studyCode: String!
    studyShortName: String
    program: [EnumProgram]!
    fundingSource: [String]
    principalInvestigator: [Investigator]!
    contact: [Investigator]!
    studyDescription: String!
    website: String
    publication: [Publication]
    acknowledgments: String
    citationStatement: String
    doId: DOI
    studyId: SdGlobalID!
  }

type StudyMetadata
  {
    externalId: [String]
    accessPolicyId: AccessPolicy
    studyId: Study!
    participantLifespanStage: [EnumParticipantLifespanStage]!
    selectionCriteria: String
    studyDesign: [EnumStudyDesign]!
    clinicalDataSourceType: [EnumClinicalDataSourceType]!
    dataCategory: [EnumDataCategory]!
    vbrId: VirtualBiorepository
    researchDomain: [EnumResearchDomain]!
    expectedNumberOfParticipants: Int!
    actualNumberOfParticipants: Int!
  }

type Subject
  {
    externalId: [String]
    accessPolicyId: AccessPolicy
    studyId: Study
    subjectId: PtGlobalID!
    subjectType: EnumSubjectType!
    organismType: String
  }

type SubjectAssertion
  {
    externalId: [String]
    accessPolicyId: AccessPolicy
    studyId: Study
    assertionId: ObGlobalID!
    subjectId: Subject
    encounterId: Encounter
    assertionProvenance: EnumAssertionProvenance
    ageAtAssertion: Int
    ageAtEvent: Int
    ageAtResolution: Int
    concept: [Concept]
    conceptSource: String
    valueConcept: [Concept]
    valueNumber: Float
    valueSource: String
    valueUnit: Concept
    valueUnitSource: String
  }

type VirtualBiorepository
  {
    externalId: [String]
    accessPolicyId: AccessPolicy
    studyId: Study
    vbrId: OrGlobalID!
    name: String
    institution: String
    contact: [Investigator]!
    website: String
    vbrReadme: String
  }
