-- # Class: Any
--     * Slot: id
-- # Abstract Class: Record Description: One row / entity within the database
--     * Slot: id
--     * Slot: access_policy_id Description: Global identifier for the access policy that applies to this row of data.
--     * Slot: study_id Description: INCLUDE Global ID for the study
-- # Class: AccessPolicy Description: The access policy that describes the controls around use of data
--     * Slot: access_policy_id Description: Global identifier for the access policy that applies to this row of data.
--     * Slot: data_use_accession Description: Accession used to provision access to the record, eg, a dbGaP phsID.
--     * Slot: data_use_permission Description: Broad category of restrictions on data use.
--     * Slot: data_use_modifier Description: Additional modifiers that limit data use.
--     * Slot: disease_limitation Description: If the access is limited to a specific disease purpose, it is specified here.
--     * Slot: access_description Description: Any additional information to support access requests.
--     * Slot: website Description: Website with more information about this entity.
-- # Class: Study Description: Study Metadata
--     * Slot: parent_study Description: The parent study for this study, if it is a nested study.
--     * Slot: study_title Description: Full Study Title
--     * Slot: study_code Description: Unique identifier for the study (generally a short acronym)
--     * Slot: study_short_name Description: Short name for the study
--     * Slot: study_description Description: Brief description of the study (2-4 sentences)
--     * Slot: website Description: Website with more information about this entity.
--     * Slot: acknowledgments Description: Funding statement and acknowledgments for this study
--     * Slot: citation_statement Description: Statement that secondary data users should use to acknowledge use of this study or dataset. E.g., "The results analyzed and <published or shown> here are based in whole or in part upon data generated by the INCLUDE (INvestigation of Co-occurring conditions across the Lifespan to Understand Down syndromeE) Project <insert accession number(s) and/or study DOI(s)>, and were accessed from the INCLUDE Data Hub and <insert other database(s)>."
--     * Slot: do_id Description: Digital Object Identifier (DOI) for this Record.
--     * Slot: access_policy_id Description: Global identifier for the access policy that applies to this row of data.
--     * Slot: study_id Description: INCLUDE Global ID for the study
-- # Class: StudyMetadata Description: Additional features about studies that may not apply to all studies
--     * Slot: study_id Description: INCLUDE Global ID for the study
--     * Slot: selection_criteria Description: Brief description of inclusion and/or exclusion criteria for the study
--     * Slot: vbr_id Description: Information about the study's Virtual Biorepository, if participating
--     * Slot: expected_number_of_participants Description: Total expected number of participants to be recruited.
--     * Slot: actual_number_of_participants Description: Total participants included at this time.
--     * Slot: access_policy_id Description: Global identifier for the access policy that applies to this row of data.
-- # Class: VirtualBiorepository Description: An organization that can provide access to specimen for further analysis.
--     * Slot: vbr_id Description: Information about the study's Virtual Biorepository, if participating
--     * Slot: name Description: Name of the entity.
--     * Slot: institution Description: Name of the institution this record is associated with.
--     * Slot: website Description: Website with more information about this entity.
--     * Slot: vbr_readme Description: Instructions for contacting or requesting samples from Virtual Biorepository, if participating
--     * Slot: access_policy_id Description: Global identifier for the access policy that applies to this row of data.
--     * Slot: study_id Description: INCLUDE Global ID for the study
-- # Class: DOI Description: A DOI is a permanent reference with metadata about a digital object.
--     * Slot: do_id Description: Digital Object Identifier (DOI) for this Record.
--     * Slot: bibliographic_reference Description: Text use to reference this Record.
--     * Slot: access_policy_id Description: Global identifier for the access policy that applies to this row of data.
--     * Slot: study_id Description: INCLUDE Global ID for the study
-- # Class: Investigator Description: An individual who made contributions to the collection, analysis, or sharing of data.
--     * Slot: id
--     * Slot: name Description: Name of the entity.
--     * Slot: institution Description: Name of the institution this record is associated with.
--     * Slot: investigator_title Description: The title of the Investigator, eg, "Assistant Professor"
--     * Slot: email Description: An email address to reach the entity.
--     * Slot: access_policy_id Description: Global identifier for the access policy that applies to this row of data.
--     * Slot: study_id Description: INCLUDE Global ID for the study
-- # Class: Publication Description: Information about a specific publication.
--     * Slot: id
--     * Slot: bibliographic_reference Description: Text use to reference this Record.
--     * Slot: website Description: Website with more information about this entity.
--     * Slot: access_policy_id Description: Global identifier for the access policy that applies to this row of data.
--     * Slot: study_id Description: INCLUDE Global ID for the study
-- # Class: Subject Description: This entity is the subject about which data or references are recorded. This includes the idea of a human participant in a study, a cell line, an animal model, or any other similar entity.
--     * Slot: subject_id Description: INCLUDE Global ID for the Subject
--     * Slot: subject_type Description: Type of entity this record represents
--     * Slot: organism_type Description: Organism Type, typically from NCBITaxon.
--     * Slot: access_policy_id Description: Global identifier for the access policy that applies to this row of data.
--     * Slot: study_id Description: INCLUDE Global ID for the study
-- # Class: Demographics Description: Basic participant demographics summary
--     * Slot: subject_id Description: INCLUDE Global ID for the Subject
--     * Slot: sex Description: Sex of Participant
--     * Slot: ethnicity Description: Ethnicity of Participant
--     * Slot: age_at_last_vital_status Description: Age in days when participant's vital status was last recorded
--     * Slot: vital_status Description: Whether participant is alive or dead
--     * Slot: age_at_first_engagement Description: Age in days of Participant at first recorded study event (enrollment, visit, observation, sample collection, survey completion, etc.). Age at enrollment is preferred, if available.
--     * Slot: access_policy_id Description: Global identifier for the access policy that applies to this row of data.
--     * Slot: study_id Description: INCLUDE Global ID for the study
-- # Class: Family Description: A group of individuals of some relation who are grouped together in a study.
--     * Slot: family_id Description: Global ID for the Family
--     * Slot: family_type Description: Describes the 'type' of study family, eg, trio.
--     * Slot: family_description Description: Free text describing the study family, such as potential inheritance or details about consanguinity
--     * Slot: consanguinity Description: Is there known or suspected consanguinity in this study family?
--     * Slot: family_study_focus Description: The specific focus of the investigation, eg, a condition.
--     * Slot: access_policy_id Description: Global identifier for the access policy that applies to this row of data.
--     * Slot: study_id Description: INCLUDE Global ID for the study
-- # Class: FamilyRelationship Description: A relationship between two Subjects. Directed as follows <family_member_id> <relationship> <subject_id> <Mother's id> <KIN:027 "isBiologicalMotherOf"> <subject_id>
--     * Slot: family_relationship_id Description: Global ID for the Family Relationship
--     * Slot: family_member_id Description: The family member Subject who is the relationship "subject".
--     * Slot: relation Description: Code definting the relationship predicate. Relationship of the "Family Member" to the "Subject", eg, mother of. Ideally uses KIN ontology.
--     * Slot: subject_id Description: The family member Subject who is the relationship "object".
--     * Slot: access_policy_id Description: Global identifier for the access policy that applies to this row of data.
--     * Slot: study_id Description: INCLUDE Global ID for the study
-- # Class: FamilyMembership Description: Designates a Subject as a member of a family with a specified role.
--     * Slot: family_membership_id Description: ID for the Family Relationship
--     * Slot: family_id Description: Global ID for the Family
--     * Slot: subject_id Description: INCLUDE Global ID for the Subject
--     * Slot: family_role Description: The "role" of this individual in this family. Could include terms like "proband", "mother", etc.
--     * Slot: access_policy_id Description: Global identifier for the access policy that applies to this row of data.
--     * Slot: study_id Description: INCLUDE Global ID for the study
-- # Class: SubjectAssertion Description: Assertion about a particular Subject. May include Conditions, Measurements, etc.
--     * Slot: assertion_id Description: INCLUDE Global ID for the Assertion
--     * Slot: subject_id Description: INCLUDE Global ID for the Subject
--     * Slot: encounter_id Description: Unique identifier for this Encounter.
--     * Slot: asserter_type Description: The original asserter of this information
--     * Slot: assertion_source_type Description: The source of this assertion from the original data
--     * Slot: age_at_assertion Description: The age in days of the Subject when the assertion was made.
--     * Slot: age_at_event Description: The age in days of the Subject at the time point which the assertion describes, eg, age of onset or when a measurement was performed.
--     * Slot: age_at_resolution Description: The age in days of the Subject when the asserted state was resolved.
--     * Slot: concept_source Description: The source text yielding the standardized concept.
--     * Slot: value_number Description: The numeric value of the assertion.
--     * Slot: value_source Description: The source text yielding the value.
--     * Slot: value_unit Description: The structured term defining the units of the value.
--     * Slot: value_unit_source Description: The source text yielding the value's units.
--     * Slot: access_policy_id Description: Global identifier for the access policy that applies to this row of data.
--     * Slot: study_id Description: INCLUDE Global ID for the study
-- # Class: Concept Description: A standardized concept with display information.
--     * Slot: concept_curie Description: The standardized curie for the term.
--     * Slot: display Description: The friendly display string of the coded term.
-- # Class: Sample Description: A functionally equivalent specimen taken from a participant or processed from such a sample.
--     * Slot: sample_id Description: The unique identifier for this Sample.
--     * Slot: biospecimen_collection_id Description: Biospecimen Collection during which this sample was generated.
--     * Slot: parent_sample_id Description: Sample from which this sample is derived
--     * Slot: sample_type Description: Type of material of which this Sample is comprised. UBERON is recommended.
--     * Slot: availability_status Description: Can this Sample be requested for further analysis?
--     * Slot: quantity_number Description: The total quantity of the specimen
--     * Slot: quantity_unit Description: The structured term defining the units of the quantity.
--     * Slot: access_policy_id Description: Global identifier for the access policy that applies to this row of data.
--     * Slot: study_id Description: INCLUDE Global ID for the study
-- # Class: BiospecimenCollection Description: A biospecimen collection event which yields one or more Samples.
--     * Slot: biospecimen_collection_id Description: Unique identifier for this Biospecimen Collection.
--     * Slot: age_at_collection Description: The age at which this biospecimen was collected in decimal years.
--     * Slot: method Description: The approach used to collect the biospecimen.
--     * Slot: site Description: The location of the specimen collection.
--     * Slot: spatial_qualifier Description: Qualifier that further refine the specific location of biospecimen collection
--     * Slot: laterality Description: Laterality that further refine the specific location of biospecimen collection
--     * Slot: encounter_id Description: Unique identifier for this Encounter.
--     * Slot: access_policy_id Description: Global identifier for the access policy that applies to this row of data.
--     * Slot: study_id Description: INCLUDE Global ID for the study
-- # Class: Aliquot Description: A specific tube or amount of a biospecimen associated with a Sample.
--     * Slot: aliquot_id Description: Unique identifier for an Aliquot.
--     * Slot: sample_id Description: The unique identifier for this Sample.
--     * Slot: availability_status Description: Can this Sample be requested for further analysis?
--     * Slot: quantity_number Description: The total quantity of the specimen
--     * Slot: quantity_unit Description: The structured term defining the units of the quantity.
--     * Slot: concentration_number Description: What is the concentration of the analyte in the Aliquot?
--     * Slot: concentration_unit Description: Units associated with the concentration of the analyte in the Aliquot.
--     * Slot: access_policy_id Description: Global identifier for the access policy that applies to this row of data.
--     * Slot: study_id Description: INCLUDE Global ID for the study
-- # Class: Encounter Description: An event at which data was collected about a participant, an intervention was made, or information about a participant was recorded.
--     * Slot: encounter_id Description: Unique identifier for this Encounter.
--     * Slot: subject_id Description: INCLUDE Global ID for the Subject
--     * Slot: encounter_definition_id Description: Unique identifier for this Encounter Definition.
--     * Slot: age_at_event Description: The age in days of the Subject at the time point which the assertion describes, eg, age of onset or when a measurement was performed.
--     * Slot: access_policy_id Description: Global identifier for the access policy that applies to this row of data.
--     * Slot: study_id Description: INCLUDE Global ID for the study
-- # Class: EncounterDefinition Description: A definition of an encounter type in this study, ie, an event at which data was collected about a participant, an intervention was made, or information about a participant was recorded. This may be something planned by a study or a type of data collection.
--     * Slot: encounter_definition_id Description: Unique identifier for this Encounter Definition.
--     * Slot: name Description: Name of the entity.
--     * Slot: description Description: Description for this entity.
--     * Slot: access_policy_id Description: Global identifier for the access policy that applies to this row of data.
--     * Slot: study_id Description: INCLUDE Global ID for the study
-- # Class: ActivityDefinition Description: A definition of an activity in this study, eg, a biospecimen collection, assay, intervention, survey, or assessment.
--     * Slot: activity_definition_id Description: Unique identifier for this Activity Definition.
--     * Slot: name Description: Name of the entity.
--     * Slot: description Description: Description for this entity.
--     * Slot: access_policy_id Description: Global identifier for the access policy that applies to this row of data.
--     * Slot: study_id Description: INCLUDE Global ID for the study
-- # Class: File Description: File
--     * Slot: file_id Description: Unique identifier for this File.
--     * Slot: filename Description: The name of the file.
--     * Slot: format Description: The format of the file.
--     * Slot: file_extension Description: Typically a 3-4 letter code at the end of a filename that identifies the file format. Empty string for no extension.
--     * Slot: data_category Description: General category of data in this Record (e.g. Clinical, Genomics, etc)
--     * Slot: data_type Description: The type of data within this file.
--     * Slot: size Description: Size of the file, in Bytes. May require BigInt or similar.
--     * Slot: internal_uri Description: URI/URL for internal access to the data. May be temporary.
--     * Slot: release_uri Description: URI/URL for controlled or open access to the data.
--     * Slot: drs_uri Description: DRS location to access the data.
--     * Slot: storage_class Description: Storage class of the object, reflecting cost and access characteristics.
--     * Slot: availability Description: Is or was this file available to users?
--     * Slot: access_policy_id Description: Global identifier for the access policy that applies to this row of data.
--     * Slot: study_id Description: INCLUDE Global ID for the study
-- # Class: FileHash Description: Type and value of a file content hash.
--     * Slot: id
--     * Slot: hash_type Description: The type of file hash, eg, md5
--     * Slot: hash_value Description: The value of the file hash
-- # Class: Assay Description: A specific assay that was performed on given subject(s) or sample(s).
--     * Slot: assay_id Description: The unique identifier for the Assay.
--     * Slot: assay_type Description: The type of assay performed.
--     * Slot: assay_source Description: The original description of the Assay performed.
--     * Slot: activity_definition_id Description: Unique identifier for this Activity Definition.
--     * Slot: access_policy_id Description: Global identifier for the access policy that applies to this row of data.
--     * Slot: study_id Description: INCLUDE Global ID for the study
-- # Class: Dataset Description: Set of files grouped together for release.
--     * Slot: dataset_id Description: Unique identifier for a Dataset.
--     * Slot: name Description: Name of the entity.
--     * Slot: description Description: Description for this entity.
--     * Slot: do_id Description: Digital Object Identifier (DOI) for this Record.
--     * Slot: data_collection_start Description: The date that data collection started. May include only a year.
--     * Slot: data_collection_end Description: The date that data collection started. May include only a year.
-- # Class: Record_external_id
--     * Slot: Record_id Description: Autocreated FK slot
--     * Slot: external_id Description: Other identifiers for this entity, eg, from the submitting study or in systems like dbGaP
-- # Class: Study_program
--     * Slot: Study_study_id Description: Autocreated FK slot
--     * Slot: program Description: Funding source(s) for the study
-- # Class: Study_funding_source
--     * Slot: Study_study_id Description: Autocreated FK slot
--     * Slot: funding_source Description: The funding source(s) of the study.
-- # Class: Study_principal_investigator
--     * Slot: Study_study_id Description: Autocreated FK slot
--     * Slot: principal_investigator_id Description: The Principal Investigator(s) responsible for the study.
-- # Class: Study_contact
--     * Slot: Study_study_id Description: Autocreated FK slot
--     * Slot: contact_id Description: The individual to contact with questions about this record.
-- # Class: Study_publication
--     * Slot: Study_study_id Description: Autocreated FK slot
--     * Slot: publication_id Description: Publications associated with this Record.
-- # Class: Study_external_id
--     * Slot: Study_study_id Description: Autocreated FK slot
--     * Slot: external_id Description: Other identifiers for this entity, eg, from the submitting study or in systems like dbGaP
-- # Class: StudyMetadata_participant_lifespan_stage
--     * Slot: StudyMetadata_study_id Description: Autocreated FK slot
--     * Slot: participant_lifespan_stage Description: Focus age group(s) of the study population
-- # Class: StudyMetadata_study_design
--     * Slot: StudyMetadata_study_id Description: Autocreated FK slot
--     * Slot: study_design_concept_curie Description: Overall design of study, including whether it is longitudinal and whether family members/unrelated controls are also enrolled
-- # Class: StudyMetadata_clinical_data_source_type
--     * Slot: StudyMetadata_study_id Description: Autocreated FK slot
--     * Slot: clinical_data_source_type Description: Source(s) of data collected from study participants
-- # Class: StudyMetadata_data_category
--     * Slot: StudyMetadata_study_id Description: Autocreated FK slot
--     * Slot: data_category_concept_curie Description: General category of data in this Record (e.g. Clinical, Genomics, etc)
-- # Class: StudyMetadata_research_domain
--     * Slot: StudyMetadata_study_id Description: Autocreated FK slot
--     * Slot: research_domain_concept_curie Description: Main research domain(s) of the study
-- # Class: StudyMetadata_external_id
--     * Slot: StudyMetadata_study_id Description: Autocreated FK slot
--     * Slot: external_id Description: Other identifiers for this entity, eg, from the submitting study or in systems like dbGaP
-- # Class: VirtualBiorepository_contact
--     * Slot: VirtualBiorepository_vbr_id Description: Autocreated FK slot
--     * Slot: contact_id Description: The individual to contact with questions about this record.
-- # Class: VirtualBiorepository_external_id
--     * Slot: VirtualBiorepository_vbr_id Description: Autocreated FK slot
--     * Slot: external_id Description: Other identifiers for this entity, eg, from the submitting study or in systems like dbGaP
-- # Class: DOI_external_id
--     * Slot: DOI_do_id Description: Autocreated FK slot
--     * Slot: external_id Description: Other identifiers for this entity, eg, from the submitting study or in systems like dbGaP
-- # Class: Investigator_external_id
--     * Slot: Investigator_id Description: Autocreated FK slot
--     * Slot: external_id Description: Other identifiers for this entity, eg, from the submitting study or in systems like dbGaP
-- # Class: Publication_external_id
--     * Slot: Publication_id Description: Autocreated FK slot
--     * Slot: external_id Description: Other identifiers for this entity, eg, from the submitting study or in systems like dbGaP
-- # Class: Subject_external_id
--     * Slot: Subject_subject_id Description: Autocreated FK slot
--     * Slot: external_id Description: Other identifiers for this entity, eg, from the submitting study or in systems like dbGaP
-- # Class: Demographics_race
--     * Slot: Demographics_subject_id Description: Autocreated FK slot
--     * Slot: race_concept_curie Description: Race of Participant
-- # Class: Demographics_external_id
--     * Slot: Demographics_subject_id Description: Autocreated FK slot
--     * Slot: external_id Description: Other identifiers for this entity, eg, from the submitting study or in systems like dbGaP
-- # Class: Family_external_id
--     * Slot: Family_family_id Description: Autocreated FK slot
--     * Slot: external_id Description: Other identifiers for this entity, eg, from the submitting study or in systems like dbGaP
-- # Class: FamilyRelationship_external_id
--     * Slot: FamilyRelationship_family_relationship_id Description: Autocreated FK slot
--     * Slot: external_id Description: Other identifiers for this entity, eg, from the submitting study or in systems like dbGaP
-- # Class: FamilyMembership_external_id
--     * Slot: FamilyMembership_family_membership_id Description: Autocreated FK slot
--     * Slot: external_id Description: Other identifiers for this entity, eg, from the submitting study or in systems like dbGaP
-- # Class: SubjectAssertion_concept
--     * Slot: SubjectAssertion_assertion_id Description: Autocreated FK slot
--     * Slot: concept_concept_curie Description: The structured term defining the meaning of the assertion.
-- # Class: SubjectAssertion_value_concept
--     * Slot: SubjectAssertion_assertion_id Description: Autocreated FK slot
--     * Slot: value_concept_concept_curie Description: The structured term defining the value of the assertion.
-- # Class: SubjectAssertion_external_id
--     * Slot: SubjectAssertion_assertion_id Description: Autocreated FK slot
--     * Slot: external_id Description: Other identifiers for this entity, eg, from the submitting study or in systems like dbGaP
-- # Class: Sample_processing
--     * Slot: Sample_sample_id Description: Autocreated FK slot
--     * Slot: processing Description: Processing that was applied to the Parent Sample or from the Biospecimen Collection that yielded this distinct sample. OBI is recommended.
-- # Class: Sample_storage_method
--     * Slot: Sample_sample_id Description: Autocreated FK slot
--     * Slot: storage_method Description: Sample storage method, eg, Frozen or with additives. OBI may be suitable, or ChEBI for additives.
-- # Class: Sample_external_id
--     * Slot: Sample_sample_id Description: Autocreated FK slot
--     * Slot: external_id Description: Other identifiers for this entity, eg, from the submitting study or in systems like dbGaP
-- # Class: BiospecimenCollection_external_id
--     * Slot: BiospecimenCollection_biospecimen_collection_id Description: Autocreated FK slot
--     * Slot: external_id Description: Other identifiers for this entity, eg, from the submitting study or in systems like dbGaP
-- # Class: Aliquot_external_id
--     * Slot: Aliquot_aliquot_id Description: Autocreated FK slot
--     * Slot: external_id Description: Other identifiers for this entity, eg, from the submitting study or in systems like dbGaP
-- # Class: Encounter_external_id
--     * Slot: Encounter_encounter_id Description: Autocreated FK slot
--     * Slot: external_id Description: Other identifiers for this entity, eg, from the submitting study or in systems like dbGaP
-- # Class: EncounterDefinition_activity_definition_id
--     * Slot: EncounterDefinition_encounter_definition_id Description: Autocreated FK slot
--     * Slot: activity_definition_id_activity_definition_id Description: Unique identifier for this Activity Definition.
-- # Class: EncounterDefinition_external_id
--     * Slot: EncounterDefinition_encounter_definition_id Description: Autocreated FK slot
--     * Slot: external_id Description: Other identifiers for this entity, eg, from the submitting study or in systems like dbGaP
-- # Class: ActivityDefinition_external_id
--     * Slot: ActivityDefinition_activity_definition_id Description: Autocreated FK slot
--     * Slot: external_id Description: Other identifiers for this entity, eg, from the submitting study or in systems like dbGaP
-- # Class: File_subject_id
--     * Slot: File_file_id Description: Autocreated FK slot
--     * Slot: subject_id_subject_id Description: INCLUDE Global ID for the Subject
-- # Class: File_sample_id
--     * Slot: File_file_id Description: Autocreated FK slot
--     * Slot: sample_id_sample_id Description: The unique identifier for this Sample.
-- # Class: File_hash
--     * Slot: File_file_id Description: Autocreated FK slot
--     * Slot: hash_id Description: File hash information
-- # Class: File_external_id
--     * Slot: File_file_id Description: Autocreated FK slot
--     * Slot: external_id Description: Other identifiers for this entity, eg, from the submitting study or in systems like dbGaP
-- # Class: Assay_subject_id
--     * Slot: Assay_assay_id Description: Autocreated FK slot
--     * Slot: subject_id_subject_id Description: INCLUDE Global ID for the Subject
-- # Class: Assay_sample_id
--     * Slot: Assay_assay_id Description: Autocreated FK slot
--     * Slot: sample_id_sample_id Description: The unique identifier for this Sample.
-- # Class: Assay_file_id
--     * Slot: Assay_assay_id Description: Autocreated FK slot
--     * Slot: file_id_file_id Description: Unique identifier for this File.
-- # Class: Assay_external_id
--     * Slot: Assay_assay_id Description: Autocreated FK slot
--     * Slot: external_id Description: Other identifiers for this entity, eg, from the submitting study or in systems like dbGaP
-- # Class: Dataset_file_id
--     * Slot: Dataset_dataset_id Description: Autocreated FK slot
--     * Slot: file_id_file_id Description: The list of files comprising this dataset.
-- # Class: Dataset_publication
--     * Slot: Dataset_dataset_id Description: Autocreated FK slot
--     * Slot: publication_id Description: Publications associated with this Record.

CREATE TABLE "Any" (
	id INTEGER NOT NULL,
	PRIMARY KEY (id)
);
CREATE INDEX "ix_Any_id" ON "Any" (id);

CREATE TABLE "AccessPolicy" (
	access_policy_id TEXT NOT NULL,
	data_use_accession TEXT,
	data_use_permission VARCHAR(11) NOT NULL,
	data_use_modifier VARCHAR(12),
	disease_limitation TEXT,
	access_description TEXT,
	website TEXT,
	PRIMARY KEY (access_policy_id)
);
CREATE INDEX "ix_AccessPolicy_access_policy_id" ON "AccessPolicy" (access_policy_id);

CREATE TABLE "Study" (
	parent_study TEXT,
	study_title TEXT NOT NULL,
	study_code TEXT NOT NULL,
	study_short_name TEXT,
	study_description TEXT NOT NULL,
	website TEXT,
	acknowledgments TEXT,
	citation_statement TEXT,
	do_id TEXT,
	access_policy_id TEXT,
	study_id TEXT NOT NULL,
	PRIMARY KEY (study_id),
	FOREIGN KEY(parent_study) REFERENCES "Study" (study_id),
	FOREIGN KEY(do_id) REFERENCES "DOI" (do_id),
	FOREIGN KEY(access_policy_id) REFERENCES "AccessPolicy" (access_policy_id)
);
CREATE INDEX "ix_Study_study_id" ON "Study" (study_id);

CREATE TABLE "DOI" (
	do_id TEXT NOT NULL,
	bibliographic_reference TEXT,
	access_policy_id TEXT,
	study_id TEXT,
	PRIMARY KEY (do_id),
	FOREIGN KEY(access_policy_id) REFERENCES "AccessPolicy" (access_policy_id),
	FOREIGN KEY(study_id) REFERENCES "Study" (study_id)
);
CREATE INDEX "ix_DOI_do_id" ON "DOI" (do_id);

CREATE TABLE "Concept" (
	concept_curie TEXT NOT NULL,
	display TEXT,
	PRIMARY KEY (concept_curie)
);
CREATE INDEX "ix_Concept_concept_curie" ON "Concept" (concept_curie);

CREATE TABLE "FileHash" (
	id INTEGER NOT NULL,
	hash_type VARCHAR(12),
	hash_value TEXT,
	PRIMARY KEY (id)
);
CREATE INDEX "ix_FileHash_id" ON "FileHash" (id);

CREATE TABLE "Record" (
	id INTEGER NOT NULL,
	access_policy_id TEXT,
	study_id TEXT,
	PRIMARY KEY (id),
	FOREIGN KEY(access_policy_id) REFERENCES "AccessPolicy" (access_policy_id),
	FOREIGN KEY(study_id) REFERENCES "Study" (study_id)
);
CREATE INDEX "ix_Record_id" ON "Record" (id);

CREATE TABLE "VirtualBiorepository" (
	vbr_id TEXT NOT NULL,
	name TEXT,
	institution TEXT,
	website TEXT,
	vbr_readme TEXT,
	access_policy_id TEXT,
	study_id TEXT,
	PRIMARY KEY (vbr_id),
	FOREIGN KEY(access_policy_id) REFERENCES "AccessPolicy" (access_policy_id),
	FOREIGN KEY(study_id) REFERENCES "Study" (study_id)
);
CREATE INDEX "ix_VirtualBiorepository_vbr_id" ON "VirtualBiorepository" (vbr_id);

CREATE TABLE "Investigator" (
	id INTEGER NOT NULL,
	name TEXT,
	institution TEXT,
	investigator_title TEXT,
	email TEXT,
	access_policy_id TEXT,
	study_id TEXT,
	PRIMARY KEY (id),
	FOREIGN KEY(access_policy_id) REFERENCES "AccessPolicy" (access_policy_id),
	FOREIGN KEY(study_id) REFERENCES "Study" (study_id)
);
CREATE INDEX "ix_Investigator_id" ON "Investigator" (id);

CREATE TABLE "Publication" (
	id INTEGER NOT NULL,
	bibliographic_reference TEXT,
	website TEXT,
	access_policy_id TEXT,
	study_id TEXT,
	PRIMARY KEY (id),
	FOREIGN KEY(access_policy_id) REFERENCES "AccessPolicy" (access_policy_id),
	FOREIGN KEY(study_id) REFERENCES "Study" (study_id)
);
CREATE INDEX "ix_Publication_id" ON "Publication" (id);

CREATE TABLE "Subject" (
	subject_id TEXT NOT NULL,
	subject_type TEXT NOT NULL,
	organism_type TEXT,
	access_policy_id TEXT,
	study_id TEXT,
	PRIMARY KEY (subject_id),
	FOREIGN KEY(subject_type) REFERENCES "Concept" (concept_curie),
	FOREIGN KEY(access_policy_id) REFERENCES "AccessPolicy" (access_policy_id),
	FOREIGN KEY(study_id) REFERENCES "Study" (study_id)
);
CREATE INDEX "ix_Subject_subject_id" ON "Subject" (subject_id);

CREATE TABLE "Family" (
	family_id TEXT NOT NULL,
	family_type VARCHAR(12),
	family_description TEXT,
	consanguinity VARCHAR(18),
	family_study_focus TEXT,
	access_policy_id TEXT,
	study_id TEXT,
	PRIMARY KEY (family_id),
	FOREIGN KEY(access_policy_id) REFERENCES "AccessPolicy" (access_policy_id),
	FOREIGN KEY(study_id) REFERENCES "Study" (study_id)
);
CREATE INDEX "ix_Family_family_id" ON "Family" (family_id);

CREATE TABLE "EncounterDefinition" (
	encounter_definition_id TEXT NOT NULL,
	name TEXT,
	description TEXT,
	access_policy_id TEXT,
	study_id TEXT,
	PRIMARY KEY (encounter_definition_id),
	FOREIGN KEY(access_policy_id) REFERENCES "AccessPolicy" (access_policy_id),
	FOREIGN KEY(study_id) REFERENCES "Study" (study_id)
);
CREATE INDEX "ix_EncounterDefinition_encounter_definition_id" ON "EncounterDefinition" (encounter_definition_id);

CREATE TABLE "ActivityDefinition" (
	activity_definition_id TEXT NOT NULL,
	name TEXT,
	description TEXT,
	access_policy_id TEXT,
	study_id TEXT,
	PRIMARY KEY (activity_definition_id),
	FOREIGN KEY(access_policy_id) REFERENCES "AccessPolicy" (access_policy_id),
	FOREIGN KEY(study_id) REFERENCES "Study" (study_id)
);
CREATE INDEX "ix_ActivityDefinition_activity_definition_id" ON "ActivityDefinition" (activity_definition_id);

CREATE TABLE "File" (
	file_id TEXT NOT NULL,
	filename TEXT,
	format VARCHAR(16),
	file_extension TEXT NOT NULL,
	data_category TEXT,
	data_type VARCHAR(14),
	size INTEGER,
	internal_uri TEXT,
	release_uri TEXT,
	drs_uri TEXT,
	storage_class TEXT,
	availability VARCHAR(18),
	access_policy_id TEXT,
	study_id TEXT,
	PRIMARY KEY (file_id),
	FOREIGN KEY(data_category) REFERENCES "Concept" (concept_curie),
	FOREIGN KEY(access_policy_id) REFERENCES "AccessPolicy" (access_policy_id),
	FOREIGN KEY(study_id) REFERENCES "Study" (study_id)
);
CREATE INDEX "ix_File_file_id" ON "File" (file_id);

CREATE TABLE "Dataset" (
	dataset_id TEXT NOT NULL,
	name TEXT,
	description TEXT,
	do_id TEXT,
	data_collection_start TEXT,
	data_collection_end TEXT,
	PRIMARY KEY (dataset_id),
	FOREIGN KEY(do_id) REFERENCES "DOI" (do_id)
);
CREATE INDEX "ix_Dataset_dataset_id" ON "Dataset" (dataset_id);

CREATE TABLE "Study_program" (
	"Study_study_id" TEXT,
	program TEXT NOT NULL,
	PRIMARY KEY ("Study_study_id", program),
	FOREIGN KEY("Study_study_id") REFERENCES "Study" (study_id)
);
CREATE INDEX "ix_Study_program_Study_study_id" ON "Study_program" ("Study_study_id");
CREATE INDEX "ix_Study_program_program" ON "Study_program" (program);

CREATE TABLE "Study_funding_source" (
	"Study_study_id" TEXT,
	funding_source TEXT,
	PRIMARY KEY ("Study_study_id", funding_source),
	FOREIGN KEY("Study_study_id") REFERENCES "Study" (study_id)
);
CREATE INDEX "ix_Study_funding_source_Study_study_id" ON "Study_funding_source" ("Study_study_id");
CREATE INDEX "ix_Study_funding_source_funding_source" ON "Study_funding_source" (funding_source);

CREATE TABLE "Study_external_id" (
	"Study_study_id" TEXT,
	external_id TEXT,
	PRIMARY KEY ("Study_study_id", external_id),
	FOREIGN KEY("Study_study_id") REFERENCES "Study" (study_id)
);
CREATE INDEX "ix_Study_external_id_external_id" ON "Study_external_id" (external_id);
CREATE INDEX "ix_Study_external_id_Study_study_id" ON "Study_external_id" ("Study_study_id");

CREATE TABLE "DOI_external_id" (
	"DOI_do_id" TEXT,
	external_id TEXT,
	PRIMARY KEY ("DOI_do_id", external_id),
	FOREIGN KEY("DOI_do_id") REFERENCES "DOI" (do_id)
);
CREATE INDEX "ix_DOI_external_id_external_id" ON "DOI_external_id" (external_id);
CREATE INDEX "ix_DOI_external_id_DOI_do_id" ON "DOI_external_id" ("DOI_do_id");

CREATE TABLE "StudyMetadata" (
	study_id TEXT NOT NULL,
	selection_criteria TEXT,
	vbr_id TEXT,
	expected_number_of_participants INTEGER NOT NULL,
	actual_number_of_participants INTEGER NOT NULL,
	access_policy_id TEXT,
	PRIMARY KEY (study_id),
	FOREIGN KEY(study_id) REFERENCES "Study" (study_id),
	FOREIGN KEY(vbr_id) REFERENCES "VirtualBiorepository" (vbr_id),
	FOREIGN KEY(access_policy_id) REFERENCES "AccessPolicy" (access_policy_id)
);
CREATE INDEX "ix_StudyMetadata_study_id" ON "StudyMetadata" (study_id);

CREATE TABLE "Demographics" (
	subject_id TEXT NOT NULL,
	sex TEXT NOT NULL,
	ethnicity TEXT NOT NULL,
	age_at_last_vital_status INTEGER,
	vital_status TEXT,
	age_at_first_engagement INTEGER,
	access_policy_id TEXT,
	study_id TEXT,
	PRIMARY KEY (subject_id),
	FOREIGN KEY(subject_id) REFERENCES "Subject" (subject_id),
	FOREIGN KEY(sex) REFERENCES "Concept" (concept_curie),
	FOREIGN KEY(ethnicity) REFERENCES "Concept" (concept_curie),
	FOREIGN KEY(vital_status) REFERENCES "Concept" (concept_curie),
	FOREIGN KEY(access_policy_id) REFERENCES "AccessPolicy" (access_policy_id),
	FOREIGN KEY(study_id) REFERENCES "Study" (study_id)
);
CREATE INDEX "ix_Demographics_subject_id" ON "Demographics" (subject_id);

CREATE TABLE "FamilyRelationship" (
	family_relationship_id TEXT NOT NULL,
	family_member_id TEXT NOT NULL,
	relation TEXT NOT NULL,
	subject_id TEXT NOT NULL,
	access_policy_id TEXT,
	study_id TEXT,
	PRIMARY KEY (family_relationship_id),
	FOREIGN KEY(family_member_id) REFERENCES "Subject" (subject_id),
	FOREIGN KEY(relation) REFERENCES "Concept" (concept_curie),
	FOREIGN KEY(subject_id) REFERENCES "Subject" (subject_id),
	FOREIGN KEY(access_policy_id) REFERENCES "AccessPolicy" (access_policy_id),
	FOREIGN KEY(study_id) REFERENCES "Study" (study_id)
);
CREATE INDEX "ix_FamilyRelationship_family_relationship_id" ON "FamilyRelationship" (family_relationship_id);

CREATE TABLE "FamilyMembership" (
	family_membership_id TEXT NOT NULL,
	family_id TEXT NOT NULL,
	subject_id TEXT NOT NULL,
	family_role TEXT,
	access_policy_id TEXT,
	study_id TEXT,
	PRIMARY KEY (family_membership_id),
	FOREIGN KEY(family_id) REFERENCES "Family" (family_id),
	FOREIGN KEY(subject_id) REFERENCES "Subject" (subject_id),
	FOREIGN KEY(family_role) REFERENCES "Concept" (concept_curie),
	FOREIGN KEY(access_policy_id) REFERENCES "AccessPolicy" (access_policy_id),
	FOREIGN KEY(study_id) REFERENCES "Study" (study_id)
);
CREATE INDEX "ix_FamilyMembership_family_membership_id" ON "FamilyMembership" (family_membership_id);

CREATE TABLE "Encounter" (
	encounter_id TEXT NOT NULL,
	subject_id TEXT,
	encounter_definition_id TEXT,
	age_at_event INTEGER,
	access_policy_id TEXT,
	study_id TEXT,
	PRIMARY KEY (encounter_id),
	FOREIGN KEY(subject_id) REFERENCES "Subject" (subject_id),
	FOREIGN KEY(encounter_definition_id) REFERENCES "EncounterDefinition" (encounter_definition_id),
	FOREIGN KEY(access_policy_id) REFERENCES "AccessPolicy" (access_policy_id),
	FOREIGN KEY(study_id) REFERENCES "Study" (study_id)
);
CREATE INDEX "ix_Encounter_encounter_id" ON "Encounter" (encounter_id);

CREATE TABLE "Assay" (
	assay_id TEXT NOT NULL,
	assay_type VARCHAR(12) NOT NULL,
	assay_source TEXT,
	activity_definition_id TEXT,
	access_policy_id TEXT,
	study_id TEXT,
	PRIMARY KEY (assay_id),
	FOREIGN KEY(activity_definition_id) REFERENCES "ActivityDefinition" (activity_definition_id),
	FOREIGN KEY(access_policy_id) REFERENCES "AccessPolicy" (access_policy_id),
	FOREIGN KEY(study_id) REFERENCES "Study" (study_id)
);
CREATE INDEX "ix_Assay_assay_id" ON "Assay" (assay_id);

CREATE TABLE "Record_external_id" (
	"Record_id" INTEGER,
	external_id TEXT,
	PRIMARY KEY ("Record_id", external_id),
	FOREIGN KEY("Record_id") REFERENCES "Record" (id)
);
CREATE INDEX "ix_Record_external_id_external_id" ON "Record_external_id" (external_id);
CREATE INDEX "ix_Record_external_id_Record_id" ON "Record_external_id" ("Record_id");

CREATE TABLE "Study_principal_investigator" (
	"Study_study_id" TEXT,
	principal_investigator_id INTEGER NOT NULL,
	PRIMARY KEY ("Study_study_id", principal_investigator_id),
	FOREIGN KEY("Study_study_id") REFERENCES "Study" (study_id),
	FOREIGN KEY(principal_investigator_id) REFERENCES "Investigator" (id)
);
CREATE INDEX "ix_Study_principal_investigator_principal_investigator_id" ON "Study_principal_investigator" (principal_investigator_id);
CREATE INDEX "ix_Study_principal_investigator_Study_study_id" ON "Study_principal_investigator" ("Study_study_id");

CREATE TABLE "Study_contact" (
	"Study_study_id" TEXT,
	contact_id INTEGER NOT NULL,
	PRIMARY KEY ("Study_study_id", contact_id),
	FOREIGN KEY("Study_study_id") REFERENCES "Study" (study_id),
	FOREIGN KEY(contact_id) REFERENCES "Investigator" (id)
);
CREATE INDEX "ix_Study_contact_Study_study_id" ON "Study_contact" ("Study_study_id");
CREATE INDEX "ix_Study_contact_contact_id" ON "Study_contact" (contact_id);

CREATE TABLE "Study_publication" (
	"Study_study_id" TEXT,
	publication_id INTEGER,
	PRIMARY KEY ("Study_study_id", publication_id),
	FOREIGN KEY("Study_study_id") REFERENCES "Study" (study_id),
	FOREIGN KEY(publication_id) REFERENCES "Publication" (id)
);
CREATE INDEX "ix_Study_publication_Study_study_id" ON "Study_publication" ("Study_study_id");
CREATE INDEX "ix_Study_publication_publication_id" ON "Study_publication" (publication_id);

CREATE TABLE "VirtualBiorepository_contact" (
	"VirtualBiorepository_vbr_id" TEXT,
	contact_id INTEGER NOT NULL,
	PRIMARY KEY ("VirtualBiorepository_vbr_id", contact_id),
	FOREIGN KEY("VirtualBiorepository_vbr_id") REFERENCES "VirtualBiorepository" (vbr_id),
	FOREIGN KEY(contact_id) REFERENCES "Investigator" (id)
);
CREATE INDEX "ix_VirtualBiorepository_contact_VirtualBiorepository_vbr_id" ON "VirtualBiorepository_contact" ("VirtualBiorepository_vbr_id");
CREATE INDEX "ix_VirtualBiorepository_contact_contact_id" ON "VirtualBiorepository_contact" (contact_id);

CREATE TABLE "VirtualBiorepository_external_id" (
	"VirtualBiorepository_vbr_id" TEXT,
	external_id TEXT,
	PRIMARY KEY ("VirtualBiorepository_vbr_id", external_id),
	FOREIGN KEY("VirtualBiorepository_vbr_id") REFERENCES "VirtualBiorepository" (vbr_id)
);
CREATE INDEX "ix_VirtualBiorepository_external_id_VirtualBiorepository_vbr_id" ON "VirtualBiorepository_external_id" ("VirtualBiorepository_vbr_id");
CREATE INDEX "ix_VirtualBiorepository_external_id_external_id" ON "VirtualBiorepository_external_id" (external_id);

CREATE TABLE "Investigator_external_id" (
	"Investigator_id" INTEGER,
	external_id TEXT,
	PRIMARY KEY ("Investigator_id", external_id),
	FOREIGN KEY("Investigator_id") REFERENCES "Investigator" (id)
);
CREATE INDEX "ix_Investigator_external_id_Investigator_id" ON "Investigator_external_id" ("Investigator_id");
CREATE INDEX "ix_Investigator_external_id_external_id" ON "Investigator_external_id" (external_id);

CREATE TABLE "Publication_external_id" (
	"Publication_id" INTEGER,
	external_id TEXT,
	PRIMARY KEY ("Publication_id", external_id),
	FOREIGN KEY("Publication_id") REFERENCES "Publication" (id)
);
CREATE INDEX "ix_Publication_external_id_external_id" ON "Publication_external_id" (external_id);
CREATE INDEX "ix_Publication_external_id_Publication_id" ON "Publication_external_id" ("Publication_id");

CREATE TABLE "Subject_external_id" (
	"Subject_subject_id" TEXT,
	external_id TEXT,
	PRIMARY KEY ("Subject_subject_id", external_id),
	FOREIGN KEY("Subject_subject_id") REFERENCES "Subject" (subject_id)
);
CREATE INDEX "ix_Subject_external_id_Subject_subject_id" ON "Subject_external_id" ("Subject_subject_id");
CREATE INDEX "ix_Subject_external_id_external_id" ON "Subject_external_id" (external_id);

CREATE TABLE "Family_external_id" (
	"Family_family_id" TEXT,
	external_id TEXT,
	PRIMARY KEY ("Family_family_id", external_id),
	FOREIGN KEY("Family_family_id") REFERENCES "Family" (family_id)
);
CREATE INDEX "ix_Family_external_id_external_id" ON "Family_external_id" (external_id);
CREATE INDEX "ix_Family_external_id_Family_family_id" ON "Family_external_id" ("Family_family_id");

CREATE TABLE "EncounterDefinition_activity_definition_id" (
	"EncounterDefinition_encounter_definition_id" TEXT,
	activity_definition_id_activity_definition_id TEXT,
	PRIMARY KEY ("EncounterDefinition_encounter_definition_id", activity_definition_id_activity_definition_id),
	FOREIGN KEY("EncounterDefinition_encounter_definition_id") REFERENCES "EncounterDefinition" (encounter_definition_id),
	FOREIGN KEY(activity_definition_id_activity_definition_id) REFERENCES "ActivityDefinition" (activity_definition_id)
);
CREATE INDEX "ix_EncounterDefinition_activity_definition_id_activity_definition_id_activity_definition_id" ON "EncounterDefinition_activity_definition_id" (activity_definition_id_activity_definition_id);
CREATE INDEX "ix_EncounterDefinition_activity_definition_id_EncounterDefinition_encounter_definition_id" ON "EncounterDefinition_activity_definition_id" ("EncounterDefinition_encounter_definition_id");

CREATE TABLE "EncounterDefinition_external_id" (
	"EncounterDefinition_encounter_definition_id" TEXT,
	external_id TEXT,
	PRIMARY KEY ("EncounterDefinition_encounter_definition_id", external_id),
	FOREIGN KEY("EncounterDefinition_encounter_definition_id") REFERENCES "EncounterDefinition" (encounter_definition_id)
);
CREATE INDEX "ix_EncounterDefinition_external_id_external_id" ON "EncounterDefinition_external_id" (external_id);
CREATE INDEX "ix_EncounterDefinition_external_id_EncounterDefinition_encounter_definition_id" ON "EncounterDefinition_external_id" ("EncounterDefinition_encounter_definition_id");

CREATE TABLE "ActivityDefinition_external_id" (
	"ActivityDefinition_activity_definition_id" TEXT,
	external_id TEXT,
	PRIMARY KEY ("ActivityDefinition_activity_definition_id", external_id),
	FOREIGN KEY("ActivityDefinition_activity_definition_id") REFERENCES "ActivityDefinition" (activity_definition_id)
);
CREATE INDEX "ix_ActivityDefinition_external_id_ActivityDefinition_activity_definition_id" ON "ActivityDefinition_external_id" ("ActivityDefinition_activity_definition_id");
CREATE INDEX "ix_ActivityDefinition_external_id_external_id" ON "ActivityDefinition_external_id" (external_id);

CREATE TABLE "File_subject_id" (
	"File_file_id" TEXT,
	subject_id_subject_id TEXT,
	PRIMARY KEY ("File_file_id", subject_id_subject_id),
	FOREIGN KEY("File_file_id") REFERENCES "File" (file_id),
	FOREIGN KEY(subject_id_subject_id) REFERENCES "Subject" (subject_id)
);
CREATE INDEX "ix_File_subject_id_File_file_id" ON "File_subject_id" ("File_file_id");
CREATE INDEX "ix_File_subject_id_subject_id_subject_id" ON "File_subject_id" (subject_id_subject_id);

CREATE TABLE "File_hash" (
	"File_file_id" TEXT,
	hash_id INTEGER,
	PRIMARY KEY ("File_file_id", hash_id),
	FOREIGN KEY("File_file_id") REFERENCES "File" (file_id),
	FOREIGN KEY(hash_id) REFERENCES "FileHash" (id)
);
CREATE INDEX "ix_File_hash_hash_id" ON "File_hash" (hash_id);
CREATE INDEX "ix_File_hash_File_file_id" ON "File_hash" ("File_file_id");

CREATE TABLE "File_external_id" (
	"File_file_id" TEXT,
	external_id TEXT,
	PRIMARY KEY ("File_file_id", external_id),
	FOREIGN KEY("File_file_id") REFERENCES "File" (file_id)
);
CREATE INDEX "ix_File_external_id_external_id" ON "File_external_id" (external_id);
CREATE INDEX "ix_File_external_id_File_file_id" ON "File_external_id" ("File_file_id");

CREATE TABLE "Dataset_file_id" (
	"Dataset_dataset_id" TEXT,
	file_id_file_id TEXT,
	PRIMARY KEY ("Dataset_dataset_id", file_id_file_id),
	FOREIGN KEY("Dataset_dataset_id") REFERENCES "Dataset" (dataset_id),
	FOREIGN KEY(file_id_file_id) REFERENCES "File" (file_id)
);
CREATE INDEX "ix_Dataset_file_id_file_id_file_id" ON "Dataset_file_id" (file_id_file_id);
CREATE INDEX "ix_Dataset_file_id_Dataset_dataset_id" ON "Dataset_file_id" ("Dataset_dataset_id");

CREATE TABLE "Dataset_publication" (
	"Dataset_dataset_id" TEXT,
	publication_id INTEGER,
	PRIMARY KEY ("Dataset_dataset_id", publication_id),
	FOREIGN KEY("Dataset_dataset_id") REFERENCES "Dataset" (dataset_id),
	FOREIGN KEY(publication_id) REFERENCES "Publication" (id)
);
CREATE INDEX "ix_Dataset_publication_Dataset_dataset_id" ON "Dataset_publication" ("Dataset_dataset_id");
CREATE INDEX "ix_Dataset_publication_publication_id" ON "Dataset_publication" (publication_id);

CREATE TABLE "SubjectAssertion" (
	assertion_id TEXT NOT NULL,
	subject_id TEXT,
	encounter_id TEXT,
	asserter_type VARCHAR(12),
	assertion_source_type VARCHAR(12),
	age_at_assertion INTEGER,
	age_at_event INTEGER,
	age_at_resolution INTEGER,
	concept_source TEXT,
	value_number FLOAT,
	value_source TEXT,
	value_unit TEXT,
	value_unit_source TEXT,
	access_policy_id TEXT,
	study_id TEXT,
	PRIMARY KEY (assertion_id),
	FOREIGN KEY(subject_id) REFERENCES "Subject" (subject_id),
	FOREIGN KEY(encounter_id) REFERENCES "Encounter" (encounter_id),
	FOREIGN KEY(value_unit) REFERENCES "Concept" (concept_curie),
	FOREIGN KEY(access_policy_id) REFERENCES "AccessPolicy" (access_policy_id),
	FOREIGN KEY(study_id) REFERENCES "Study" (study_id)
);
CREATE INDEX "ix_SubjectAssertion_assertion_id" ON "SubjectAssertion" (assertion_id);

CREATE TABLE "BiospecimenCollection" (
	biospecimen_collection_id TEXT NOT NULL,
	age_at_collection FLOAT,
	method VARCHAR,
	site TEXT,
	spatial_qualifier TEXT,
	laterality TEXT,
	encounter_id TEXT,
	access_policy_id TEXT,
	study_id TEXT,
	PRIMARY KEY (biospecimen_collection_id),
	FOREIGN KEY(site) REFERENCES "Concept" (concept_curie),
	FOREIGN KEY(spatial_qualifier) REFERENCES "Concept" (concept_curie),
	FOREIGN KEY(laterality) REFERENCES "Concept" (concept_curie),
	FOREIGN KEY(encounter_id) REFERENCES "Encounter" (encounter_id),
	FOREIGN KEY(access_policy_id) REFERENCES "AccessPolicy" (access_policy_id),
	FOREIGN KEY(study_id) REFERENCES "Study" (study_id)
);
CREATE INDEX "ix_BiospecimenCollection_biospecimen_collection_id" ON "BiospecimenCollection" (biospecimen_collection_id);

CREATE TABLE "StudyMetadata_participant_lifespan_stage" (
	"StudyMetadata_study_id" TEXT,
	participant_lifespan_stage VARCHAR NOT NULL,
	PRIMARY KEY ("StudyMetadata_study_id", participant_lifespan_stage),
	FOREIGN KEY("StudyMetadata_study_id") REFERENCES "StudyMetadata" (study_id)
);
CREATE INDEX "ix_StudyMetadata_participant_lifespan_stage_StudyMetadata_study_id" ON "StudyMetadata_participant_lifespan_stage" ("StudyMetadata_study_id");
CREATE INDEX "ix_StudyMetadata_participant_lifespan_stage_participant_lifespan_stage" ON "StudyMetadata_participant_lifespan_stage" (participant_lifespan_stage);

CREATE TABLE "StudyMetadata_study_design" (
	"StudyMetadata_study_id" TEXT,
	study_design_concept_curie TEXT NOT NULL,
	PRIMARY KEY ("StudyMetadata_study_id", study_design_concept_curie),
	FOREIGN KEY("StudyMetadata_study_id") REFERENCES "StudyMetadata" (study_id),
	FOREIGN KEY(study_design_concept_curie) REFERENCES "Concept" (concept_curie)
);
CREATE INDEX "ix_StudyMetadata_study_design_study_design_concept_curie" ON "StudyMetadata_study_design" (study_design_concept_curie);
CREATE INDEX "ix_StudyMetadata_study_design_StudyMetadata_study_id" ON "StudyMetadata_study_design" ("StudyMetadata_study_id");

CREATE TABLE "StudyMetadata_clinical_data_source_type" (
	"StudyMetadata_study_id" TEXT,
	clinical_data_source_type VARCHAR(12) NOT NULL,
	PRIMARY KEY ("StudyMetadata_study_id", clinical_data_source_type),
	FOREIGN KEY("StudyMetadata_study_id") REFERENCES "StudyMetadata" (study_id)
);
CREATE INDEX "ix_StudyMetadata_clinical_data_source_type_StudyMetadata_study_id" ON "StudyMetadata_clinical_data_source_type" ("StudyMetadata_study_id");
CREATE INDEX "ix_StudyMetadata_clinical_data_source_type_clinical_data_source_type" ON "StudyMetadata_clinical_data_source_type" (clinical_data_source_type);

CREATE TABLE "StudyMetadata_data_category" (
	"StudyMetadata_study_id" TEXT,
	data_category_concept_curie TEXT NOT NULL,
	PRIMARY KEY ("StudyMetadata_study_id", data_category_concept_curie),
	FOREIGN KEY("StudyMetadata_study_id") REFERENCES "StudyMetadata" (study_id),
	FOREIGN KEY(data_category_concept_curie) REFERENCES "Concept" (concept_curie)
);
CREATE INDEX "ix_StudyMetadata_data_category_StudyMetadata_study_id" ON "StudyMetadata_data_category" ("StudyMetadata_study_id");
CREATE INDEX "ix_StudyMetadata_data_category_data_category_concept_curie" ON "StudyMetadata_data_category" (data_category_concept_curie);

CREATE TABLE "StudyMetadata_research_domain" (
	"StudyMetadata_study_id" TEXT,
	research_domain_concept_curie TEXT NOT NULL,
	PRIMARY KEY ("StudyMetadata_study_id", research_domain_concept_curie),
	FOREIGN KEY("StudyMetadata_study_id") REFERENCES "StudyMetadata" (study_id),
	FOREIGN KEY(research_domain_concept_curie) REFERENCES "Concept" (concept_curie)
);
CREATE INDEX "ix_StudyMetadata_research_domain_research_domain_concept_curie" ON "StudyMetadata_research_domain" (research_domain_concept_curie);
CREATE INDEX "ix_StudyMetadata_research_domain_StudyMetadata_study_id" ON "StudyMetadata_research_domain" ("StudyMetadata_study_id");

CREATE TABLE "StudyMetadata_external_id" (
	"StudyMetadata_study_id" TEXT,
	external_id TEXT,
	PRIMARY KEY ("StudyMetadata_study_id", external_id),
	FOREIGN KEY("StudyMetadata_study_id") REFERENCES "StudyMetadata" (study_id)
);
CREATE INDEX "ix_StudyMetadata_external_id_external_id" ON "StudyMetadata_external_id" (external_id);
CREATE INDEX "ix_StudyMetadata_external_id_StudyMetadata_study_id" ON "StudyMetadata_external_id" ("StudyMetadata_study_id");

CREATE TABLE "Demographics_race" (
	"Demographics_subject_id" TEXT,
	race_concept_curie TEXT NOT NULL,
	PRIMARY KEY ("Demographics_subject_id", race_concept_curie),
	FOREIGN KEY("Demographics_subject_id") REFERENCES "Demographics" (subject_id),
	FOREIGN KEY(race_concept_curie) REFERENCES "Concept" (concept_curie)
);
CREATE INDEX "ix_Demographics_race_race_concept_curie" ON "Demographics_race" (race_concept_curie);
CREATE INDEX "ix_Demographics_race_Demographics_subject_id" ON "Demographics_race" ("Demographics_subject_id");

CREATE TABLE "Demographics_external_id" (
	"Demographics_subject_id" TEXT,
	external_id TEXT,
	PRIMARY KEY ("Demographics_subject_id", external_id),
	FOREIGN KEY("Demographics_subject_id") REFERENCES "Demographics" (subject_id)
);
CREATE INDEX "ix_Demographics_external_id_external_id" ON "Demographics_external_id" (external_id);
CREATE INDEX "ix_Demographics_external_id_Demographics_subject_id" ON "Demographics_external_id" ("Demographics_subject_id");

CREATE TABLE "FamilyRelationship_external_id" (
	"FamilyRelationship_family_relationship_id" TEXT,
	external_id TEXT,
	PRIMARY KEY ("FamilyRelationship_family_relationship_id", external_id),
	FOREIGN KEY("FamilyRelationship_family_relationship_id") REFERENCES "FamilyRelationship" (family_relationship_id)
);
CREATE INDEX "ix_FamilyRelationship_external_id_external_id" ON "FamilyRelationship_external_id" (external_id);
CREATE INDEX "ix_FamilyRelationship_external_id_FamilyRelationship_family_relationship_id" ON "FamilyRelationship_external_id" ("FamilyRelationship_family_relationship_id");

CREATE TABLE "FamilyMembership_external_id" (
	"FamilyMembership_family_membership_id" TEXT,
	external_id TEXT,
	PRIMARY KEY ("FamilyMembership_family_membership_id", external_id),
	FOREIGN KEY("FamilyMembership_family_membership_id") REFERENCES "FamilyMembership" (family_membership_id)
);
CREATE INDEX "ix_FamilyMembership_external_id_FamilyMembership_family_membership_id" ON "FamilyMembership_external_id" ("FamilyMembership_family_membership_id");
CREATE INDEX "ix_FamilyMembership_external_id_external_id" ON "FamilyMembership_external_id" (external_id);

CREATE TABLE "Encounter_external_id" (
	"Encounter_encounter_id" TEXT,
	external_id TEXT,
	PRIMARY KEY ("Encounter_encounter_id", external_id),
	FOREIGN KEY("Encounter_encounter_id") REFERENCES "Encounter" (encounter_id)
);
CREATE INDEX "ix_Encounter_external_id_external_id" ON "Encounter_external_id" (external_id);
CREATE INDEX "ix_Encounter_external_id_Encounter_encounter_id" ON "Encounter_external_id" ("Encounter_encounter_id");

CREATE TABLE "Assay_subject_id" (
	"Assay_assay_id" TEXT,
	subject_id_subject_id TEXT,
	PRIMARY KEY ("Assay_assay_id", subject_id_subject_id),
	FOREIGN KEY("Assay_assay_id") REFERENCES "Assay" (assay_id),
	FOREIGN KEY(subject_id_subject_id) REFERENCES "Subject" (subject_id)
);
CREATE INDEX "ix_Assay_subject_id_subject_id_subject_id" ON "Assay_subject_id" (subject_id_subject_id);
CREATE INDEX "ix_Assay_subject_id_Assay_assay_id" ON "Assay_subject_id" ("Assay_assay_id");

CREATE TABLE "Assay_file_id" (
	"Assay_assay_id" TEXT,
	file_id_file_id TEXT,
	PRIMARY KEY ("Assay_assay_id", file_id_file_id),
	FOREIGN KEY("Assay_assay_id") REFERENCES "Assay" (assay_id),
	FOREIGN KEY(file_id_file_id) REFERENCES "File" (file_id)
);
CREATE INDEX "ix_Assay_file_id_file_id_file_id" ON "Assay_file_id" (file_id_file_id);
CREATE INDEX "ix_Assay_file_id_Assay_assay_id" ON "Assay_file_id" ("Assay_assay_id");

CREATE TABLE "Assay_external_id" (
	"Assay_assay_id" TEXT,
	external_id TEXT,
	PRIMARY KEY ("Assay_assay_id", external_id),
	FOREIGN KEY("Assay_assay_id") REFERENCES "Assay" (assay_id)
);
CREATE INDEX "ix_Assay_external_id_external_id" ON "Assay_external_id" (external_id);
CREATE INDEX "ix_Assay_external_id_Assay_assay_id" ON "Assay_external_id" ("Assay_assay_id");

CREATE TABLE "Sample" (
	sample_id TEXT NOT NULL,
	biospecimen_collection_id TEXT,
	parent_sample_id TEXT,
	sample_type TEXT NOT NULL,
	availability_status VARCHAR(18),
	quantity_number FLOAT,
	quantity_unit TEXT,
	access_policy_id TEXT,
	study_id TEXT,
	PRIMARY KEY (sample_id),
	FOREIGN KEY(biospecimen_collection_id) REFERENCES "BiospecimenCollection" (biospecimen_collection_id),
	FOREIGN KEY(parent_sample_id) REFERENCES "Sample" (sample_id),
	FOREIGN KEY(quantity_unit) REFERENCES "Concept" (concept_curie),
	FOREIGN KEY(access_policy_id) REFERENCES "AccessPolicy" (access_policy_id),
	FOREIGN KEY(study_id) REFERENCES "Study" (study_id)
);
CREATE INDEX "ix_Sample_sample_id" ON "Sample" (sample_id);

CREATE TABLE "SubjectAssertion_concept" (
	"SubjectAssertion_assertion_id" TEXT,
	concept_concept_curie TEXT,
	PRIMARY KEY ("SubjectAssertion_assertion_id", concept_concept_curie),
	FOREIGN KEY("SubjectAssertion_assertion_id") REFERENCES "SubjectAssertion" (assertion_id),
	FOREIGN KEY(concept_concept_curie) REFERENCES "Concept" (concept_curie)
);
CREATE INDEX "ix_SubjectAssertion_concept_concept_concept_curie" ON "SubjectAssertion_concept" (concept_concept_curie);
CREATE INDEX "ix_SubjectAssertion_concept_SubjectAssertion_assertion_id" ON "SubjectAssertion_concept" ("SubjectAssertion_assertion_id");

CREATE TABLE "SubjectAssertion_value_concept" (
	"SubjectAssertion_assertion_id" TEXT,
	value_concept_concept_curie TEXT,
	PRIMARY KEY ("SubjectAssertion_assertion_id", value_concept_concept_curie),
	FOREIGN KEY("SubjectAssertion_assertion_id") REFERENCES "SubjectAssertion" (assertion_id),
	FOREIGN KEY(value_concept_concept_curie) REFERENCES "Concept" (concept_curie)
);
CREATE INDEX "ix_SubjectAssertion_value_concept_SubjectAssertion_assertion_id" ON "SubjectAssertion_value_concept" ("SubjectAssertion_assertion_id");
CREATE INDEX "ix_SubjectAssertion_value_concept_value_concept_concept_curie" ON "SubjectAssertion_value_concept" (value_concept_concept_curie);

CREATE TABLE "SubjectAssertion_external_id" (
	"SubjectAssertion_assertion_id" TEXT,
	external_id TEXT,
	PRIMARY KEY ("SubjectAssertion_assertion_id", external_id),
	FOREIGN KEY("SubjectAssertion_assertion_id") REFERENCES "SubjectAssertion" (assertion_id)
);
CREATE INDEX "ix_SubjectAssertion_external_id_SubjectAssertion_assertion_id" ON "SubjectAssertion_external_id" ("SubjectAssertion_assertion_id");
CREATE INDEX "ix_SubjectAssertion_external_id_external_id" ON "SubjectAssertion_external_id" (external_id);

CREATE TABLE "BiospecimenCollection_external_id" (
	"BiospecimenCollection_biospecimen_collection_id" TEXT,
	external_id TEXT,
	PRIMARY KEY ("BiospecimenCollection_biospecimen_collection_id", external_id),
	FOREIGN KEY("BiospecimenCollection_biospecimen_collection_id") REFERENCES "BiospecimenCollection" (biospecimen_collection_id)
);
CREATE INDEX "ix_BiospecimenCollection_external_id_BiospecimenCollection_biospecimen_collection_id" ON "BiospecimenCollection_external_id" ("BiospecimenCollection_biospecimen_collection_id");
CREATE INDEX "ix_BiospecimenCollection_external_id_external_id" ON "BiospecimenCollection_external_id" (external_id);

CREATE TABLE "Aliquot" (
	aliquot_id TEXT NOT NULL,
	sample_id TEXT,
	availability_status VARCHAR(18),
	quantity_number FLOAT,
	quantity_unit TEXT,
	concentration_number FLOAT,
	concentration_unit TEXT,
	access_policy_id TEXT,
	study_id TEXT,
	PRIMARY KEY (aliquot_id),
	FOREIGN KEY(sample_id) REFERENCES "Sample" (sample_id),
	FOREIGN KEY(quantity_unit) REFERENCES "Concept" (concept_curie),
	FOREIGN KEY(concentration_unit) REFERENCES "Concept" (concept_curie),
	FOREIGN KEY(access_policy_id) REFERENCES "AccessPolicy" (access_policy_id),
	FOREIGN KEY(study_id) REFERENCES "Study" (study_id)
);
CREATE INDEX "ix_Aliquot_aliquot_id" ON "Aliquot" (aliquot_id);

CREATE TABLE "Sample_processing" (
	"Sample_sample_id" TEXT,
	processing TEXT,
	PRIMARY KEY ("Sample_sample_id", processing),
	FOREIGN KEY("Sample_sample_id") REFERENCES "Sample" (sample_id)
);
CREATE INDEX "ix_Sample_processing_Sample_sample_id" ON "Sample_processing" ("Sample_sample_id");
CREATE INDEX "ix_Sample_processing_processing" ON "Sample_processing" (processing);

CREATE TABLE "Sample_storage_method" (
	"Sample_sample_id" TEXT,
	storage_method TEXT,
	PRIMARY KEY ("Sample_sample_id", storage_method),
	FOREIGN KEY("Sample_sample_id") REFERENCES "Sample" (sample_id)
);
CREATE INDEX "ix_Sample_storage_method_storage_method" ON "Sample_storage_method" (storage_method);
CREATE INDEX "ix_Sample_storage_method_Sample_sample_id" ON "Sample_storage_method" ("Sample_sample_id");

CREATE TABLE "Sample_external_id" (
	"Sample_sample_id" TEXT,
	external_id TEXT,
	PRIMARY KEY ("Sample_sample_id", external_id),
	FOREIGN KEY("Sample_sample_id") REFERENCES "Sample" (sample_id)
);
CREATE INDEX "ix_Sample_external_id_external_id" ON "Sample_external_id" (external_id);
CREATE INDEX "ix_Sample_external_id_Sample_sample_id" ON "Sample_external_id" ("Sample_sample_id");

CREATE TABLE "File_sample_id" (
	"File_file_id" TEXT,
	sample_id_sample_id TEXT,
	PRIMARY KEY ("File_file_id", sample_id_sample_id),
	FOREIGN KEY("File_file_id") REFERENCES "File" (file_id),
	FOREIGN KEY(sample_id_sample_id) REFERENCES "Sample" (sample_id)
);
CREATE INDEX "ix_File_sample_id_File_file_id" ON "File_sample_id" ("File_file_id");
CREATE INDEX "ix_File_sample_id_sample_id_sample_id" ON "File_sample_id" (sample_id_sample_id);

CREATE TABLE "Assay_sample_id" (
	"Assay_assay_id" TEXT,
	sample_id_sample_id TEXT,
	PRIMARY KEY ("Assay_assay_id", sample_id_sample_id),
	FOREIGN KEY("Assay_assay_id") REFERENCES "Assay" (assay_id),
	FOREIGN KEY(sample_id_sample_id) REFERENCES "Sample" (sample_id)
);
CREATE INDEX "ix_Assay_sample_id_sample_id_sample_id" ON "Assay_sample_id" (sample_id_sample_id);
CREATE INDEX "ix_Assay_sample_id_Assay_assay_id" ON "Assay_sample_id" ("Assay_assay_id");

CREATE TABLE "Aliquot_external_id" (
	"Aliquot_aliquot_id" TEXT,
	external_id TEXT,
	PRIMARY KEY ("Aliquot_aliquot_id", external_id),
	FOREIGN KEY("Aliquot_aliquot_id") REFERENCES "Aliquot" (aliquot_id)
);
CREATE INDEX "ix_Aliquot_external_id_Aliquot_aliquot_id" ON "Aliquot_external_id" ("Aliquot_aliquot_id");
CREATE INDEX "ix_Aliquot_external_id_external_id" ON "Aliquot_external_id" (external_id);
